### ISSUE TITLE
NNMap.txt

### ISSUE THREAD

**Issue by luan373** [elazar55/Angry-Bird#1]
Hello, Elazar55

I have tested your Angry-Bird but the bot requires NMap.txt, can you post?

Thanks and congratulations for the bot

**Comment by elazar55** [comment]
NNMap is generated by the NNMap repo

**Comment by luan373** [comment]
Ok, thank you

And about this: 
'truth_buy' - undeclared identifier	Angry-Bird.mq4	104	22
'truth_sell' - undeclared identifier	Angry-Bird.mq4	105	22

**Comment by elazar55** [comment]
You need to put the generated file at the directory that's at the top (and
change it)
